// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/ImageAnnotations.proto

#ifndef PROTOBUF_INCLUDED_foxglove_2fImageAnnotations_2eproto
#define PROTOBUF_INCLUDED_foxglove_2fImageAnnotations_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "foxglove/CircleAnnotation.pb.h"
#include "foxglove/PointsAnnotation.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fImageAnnotations_2eproto 

namespace protobuf_foxglove_2fImageAnnotations_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_foxglove_2fImageAnnotations_2eproto
namespace foxglove {
class ImageAnnotations;
class ImageAnnotationsDefaultTypeInternal;
extern ImageAnnotationsDefaultTypeInternal _ImageAnnotations_default_instance_;
}  // namespace foxglove
namespace google {
namespace protobuf {
template<> ::foxglove::ImageAnnotations* Arena::CreateMaybeMessage<::foxglove::ImageAnnotations>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace foxglove {

// ===================================================================

class ImageAnnotations : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:foxglove.ImageAnnotations) */ {
 public:
  ImageAnnotations();
  virtual ~ImageAnnotations();

  ImageAnnotations(const ImageAnnotations& from);

  inline ImageAnnotations& operator=(const ImageAnnotations& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ImageAnnotations(ImageAnnotations&& from) noexcept
    : ImageAnnotations() {
    *this = ::std::move(from);
  }

  inline ImageAnnotations& operator=(ImageAnnotations&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ImageAnnotations& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImageAnnotations* internal_default_instance() {
    return reinterpret_cast<const ImageAnnotations*>(
               &_ImageAnnotations_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ImageAnnotations* other);
  friend void swap(ImageAnnotations& a, ImageAnnotations& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ImageAnnotations* New() const final {
    return CreateMaybeMessage<ImageAnnotations>(NULL);
  }

  ImageAnnotations* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ImageAnnotations>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ImageAnnotations& from);
  void MergeFrom(const ImageAnnotations& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageAnnotations* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .foxglove.CircleAnnotation circles = 1;
  int circles_size() const;
  void clear_circles();
  static const int kCirclesFieldNumber = 1;
  ::foxglove::CircleAnnotation* mutable_circles(int index);
  ::google::protobuf::RepeatedPtrField< ::foxglove::CircleAnnotation >*
      mutable_circles();
  const ::foxglove::CircleAnnotation& circles(int index) const;
  ::foxglove::CircleAnnotation* add_circles();
  const ::google::protobuf::RepeatedPtrField< ::foxglove::CircleAnnotation >&
      circles() const;

  // repeated .foxglove.PointsAnnotation points = 2;
  int points_size() const;
  void clear_points();
  static const int kPointsFieldNumber = 2;
  ::foxglove::PointsAnnotation* mutable_points(int index);
  ::google::protobuf::RepeatedPtrField< ::foxglove::PointsAnnotation >*
      mutable_points();
  const ::foxglove::PointsAnnotation& points(int index) const;
  ::foxglove::PointsAnnotation* add_points();
  const ::google::protobuf::RepeatedPtrField< ::foxglove::PointsAnnotation >&
      points() const;

  // @@protoc_insertion_point(class_scope:foxglove.ImageAnnotations)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::foxglove::CircleAnnotation > circles_;
  ::google::protobuf::RepeatedPtrField< ::foxglove::PointsAnnotation > points_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_foxglove_2fImageAnnotations_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ImageAnnotations

// repeated .foxglove.CircleAnnotation circles = 1;
inline int ImageAnnotations::circles_size() const {
  return circles_.size();
}
inline ::foxglove::CircleAnnotation* ImageAnnotations::mutable_circles(int index) {
  // @@protoc_insertion_point(field_mutable:foxglove.ImageAnnotations.circles)
  return circles_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::foxglove::CircleAnnotation >*
ImageAnnotations::mutable_circles() {
  // @@protoc_insertion_point(field_mutable_list:foxglove.ImageAnnotations.circles)
  return &circles_;
}
inline const ::foxglove::CircleAnnotation& ImageAnnotations::circles(int index) const {
  // @@protoc_insertion_point(field_get:foxglove.ImageAnnotations.circles)
  return circles_.Get(index);
}
inline ::foxglove::CircleAnnotation* ImageAnnotations::add_circles() {
  // @@protoc_insertion_point(field_add:foxglove.ImageAnnotations.circles)
  return circles_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::foxglove::CircleAnnotation >&
ImageAnnotations::circles() const {
  // @@protoc_insertion_point(field_list:foxglove.ImageAnnotations.circles)
  return circles_;
}

// repeated .foxglove.PointsAnnotation points = 2;
inline int ImageAnnotations::points_size() const {
  return points_.size();
}
inline ::foxglove::PointsAnnotation* ImageAnnotations::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:foxglove.ImageAnnotations.points)
  return points_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::foxglove::PointsAnnotation >*
ImageAnnotations::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:foxglove.ImageAnnotations.points)
  return &points_;
}
inline const ::foxglove::PointsAnnotation& ImageAnnotations::points(int index) const {
  // @@protoc_insertion_point(field_get:foxglove.ImageAnnotations.points)
  return points_.Get(index);
}
inline ::foxglove::PointsAnnotation* ImageAnnotations::add_points() {
  // @@protoc_insertion_point(field_add:foxglove.ImageAnnotations.points)
  return points_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::foxglove::PointsAnnotation >&
ImageAnnotations::points() const {
  // @@protoc_insertion_point(field_list:foxglove.ImageAnnotations.points)
  return points_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace foxglove

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_foxglove_2fImageAnnotations_2eproto
