// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/PosesInFrame.proto

#ifndef PROTOBUF_INCLUDED_foxglove_2fPosesInFrame_2eproto
#define PROTOBUF_INCLUDED_foxglove_2fPosesInFrame_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "foxglove/Pose.pb.h"
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fPosesInFrame_2eproto 

namespace protobuf_foxglove_2fPosesInFrame_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_foxglove_2fPosesInFrame_2eproto
namespace foxglove {
class PosesInFrame;
class PosesInFrameDefaultTypeInternal;
extern PosesInFrameDefaultTypeInternal _PosesInFrame_default_instance_;
}  // namespace foxglove
namespace google {
namespace protobuf {
template<> ::foxglove::PosesInFrame* Arena::CreateMaybeMessage<::foxglove::PosesInFrame>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace foxglove {

// ===================================================================

class PosesInFrame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:foxglove.PosesInFrame) */ {
 public:
  PosesInFrame();
  virtual ~PosesInFrame();

  PosesInFrame(const PosesInFrame& from);

  inline PosesInFrame& operator=(const PosesInFrame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PosesInFrame(PosesInFrame&& from) noexcept
    : PosesInFrame() {
    *this = ::std::move(from);
  }

  inline PosesInFrame& operator=(PosesInFrame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PosesInFrame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PosesInFrame* internal_default_instance() {
    return reinterpret_cast<const PosesInFrame*>(
               &_PosesInFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PosesInFrame* other);
  friend void swap(PosesInFrame& a, PosesInFrame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PosesInFrame* New() const final {
    return CreateMaybeMessage<PosesInFrame>(NULL);
  }

  PosesInFrame* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PosesInFrame>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PosesInFrame& from);
  void MergeFrom(const PosesInFrame& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PosesInFrame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .foxglove.Pose poses = 3;
  int poses_size() const;
  void clear_poses();
  static const int kPosesFieldNumber = 3;
  ::foxglove::Pose* mutable_poses(int index);
  ::google::protobuf::RepeatedPtrField< ::foxglove::Pose >*
      mutable_poses();
  const ::foxglove::Pose& poses(int index) const;
  ::foxglove::Pose* add_poses();
  const ::google::protobuf::RepeatedPtrField< ::foxglove::Pose >&
      poses() const;

  // string frame_id = 2;
  void clear_frame_id();
  static const int kFrameIdFieldNumber = 2;
  const ::std::string& frame_id() const;
  void set_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_frame_id(::std::string&& value);
  #endif
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  ::std::string* mutable_frame_id();
  ::std::string* release_frame_id();
  void set_allocated_frame_id(::std::string* frame_id);

  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  public:
  const ::google::protobuf::Timestamp& timestamp() const;
  ::google::protobuf::Timestamp* release_timestamp();
  ::google::protobuf::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* timestamp);

  // @@protoc_insertion_point(class_scope:foxglove.PosesInFrame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::foxglove::Pose > poses_;
  ::google::protobuf::internal::ArenaStringPtr frame_id_;
  ::google::protobuf::Timestamp* timestamp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_foxglove_2fPosesInFrame_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PosesInFrame

// .google.protobuf.Timestamp timestamp = 1;
inline bool PosesInFrame::has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != NULL;
}
inline const ::google::protobuf::Timestamp& PosesInFrame::_internal_timestamp() const {
  return *timestamp_;
}
inline const ::google::protobuf::Timestamp& PosesInFrame::timestamp() const {
  const ::google::protobuf::Timestamp* p = timestamp_;
  // @@protoc_insertion_point(field_get:foxglove.PosesInFrame.timestamp)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Timestamp*>(
      &::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* PosesInFrame::release_timestamp() {
  // @@protoc_insertion_point(field_release:foxglove.PosesInFrame.timestamp)
  
  ::google::protobuf::Timestamp* temp = timestamp_;
  timestamp_ = NULL;
  return temp;
}
inline ::google::protobuf::Timestamp* PosesInFrame::mutable_timestamp() {
  
  if (timestamp_ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::Timestamp>(GetArenaNoVirtual());
    timestamp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:foxglove.PosesInFrame.timestamp)
  return timestamp_;
}
inline void PosesInFrame::set_allocated_timestamp(::google::protobuf::Timestamp* timestamp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:foxglove.PosesInFrame.timestamp)
}

// string frame_id = 2;
inline void PosesInFrame::clear_frame_id() {
  frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PosesInFrame::frame_id() const {
  // @@protoc_insertion_point(field_get:foxglove.PosesInFrame.frame_id)
  return frame_id_.GetNoArena();
}
inline void PosesInFrame::set_frame_id(const ::std::string& value) {
  
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:foxglove.PosesInFrame.frame_id)
}
#if LANG_CXX11
inline void PosesInFrame::set_frame_id(::std::string&& value) {
  
  frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:foxglove.PosesInFrame.frame_id)
}
#endif
inline void PosesInFrame::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:foxglove.PosesInFrame.frame_id)
}
inline void PosesInFrame::set_frame_id(const char* value, size_t size) {
  
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:foxglove.PosesInFrame.frame_id)
}
inline ::std::string* PosesInFrame::mutable_frame_id() {
  
  // @@protoc_insertion_point(field_mutable:foxglove.PosesInFrame.frame_id)
  return frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PosesInFrame::release_frame_id() {
  // @@protoc_insertion_point(field_release:foxglove.PosesInFrame.frame_id)
  
  return frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PosesInFrame::set_allocated_frame_id(::std::string* frame_id) {
  if (frame_id != NULL) {
    
  } else {
    
  }
  frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_id);
  // @@protoc_insertion_point(field_set_allocated:foxglove.PosesInFrame.frame_id)
}

// repeated .foxglove.Pose poses = 3;
inline int PosesInFrame::poses_size() const {
  return poses_.size();
}
inline ::foxglove::Pose* PosesInFrame::mutable_poses(int index) {
  // @@protoc_insertion_point(field_mutable:foxglove.PosesInFrame.poses)
  return poses_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::foxglove::Pose >*
PosesInFrame::mutable_poses() {
  // @@protoc_insertion_point(field_mutable_list:foxglove.PosesInFrame.poses)
  return &poses_;
}
inline const ::foxglove::Pose& PosesInFrame::poses(int index) const {
  // @@protoc_insertion_point(field_get:foxglove.PosesInFrame.poses)
  return poses_.Get(index);
}
inline ::foxglove::Pose* PosesInFrame::add_poses() {
  // @@protoc_insertion_point(field_add:foxglove.PosesInFrame.poses)
  return poses_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::foxglove::Pose >&
PosesInFrame::poses() const {
  // @@protoc_insertion_point(field_list:foxglove.PosesInFrame.poses)
  return poses_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace foxglove

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_foxglove_2fPosesInFrame_2eproto
