// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/PointsAnnotation.proto

#include "foxglove/PointsAnnotation.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_foxglove_2fColor_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fColor_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Color;
}  // namespace protobuf_foxglove_2fColor_2eproto
namespace protobuf_foxglove_2fPoint2_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fPoint2_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Point2;
}  // namespace protobuf_foxglove_2fPoint2_2eproto
namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2ftimestamp_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Timestamp;
}  // namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto
namespace foxglove {
class PointsAnnotationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PointsAnnotation>
      _instance;
} _PointsAnnotation_default_instance_;
}  // namespace foxglove
namespace protobuf_foxglove_2fPointsAnnotation_2eproto {
static void InitDefaultsPointsAnnotation() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::foxglove::_PointsAnnotation_default_instance_;
    new (ptr) ::foxglove::PointsAnnotation();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::foxglove::PointsAnnotation::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_PointsAnnotation =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsPointsAnnotation}, {
      &protobuf_google_2fprotobuf_2ftimestamp_2eproto::scc_info_Timestamp.base,
      &protobuf_foxglove_2fPoint2_2eproto::scc_info_Point2.base,
      &protobuf_foxglove_2fColor_2eproto::scc_info_Color.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_PointsAnnotation.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::PointsAnnotation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::PointsAnnotation, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::PointsAnnotation, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::PointsAnnotation, points_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::PointsAnnotation, outline_colors_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::PointsAnnotation, fill_color_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::foxglove::PointsAnnotation)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::foxglove::_PointsAnnotation_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "foxglove/PointsAnnotation.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\037foxglove/PointsAnnotation.proto\022\010foxgl"
      "ove\032\024foxglove/Color.proto\032\025foxglove/Poin"
      "t2.proto\032\037google/protobuf/timestamp.prot"
      "o\"\257\002\n\020PointsAnnotation\022-\n\ttimestamp\030\001 \001("
      "\0132\032.google.protobuf.Timestamp\022-\n\004type\030\002 "
      "\001(\0162\037.foxglove.PointsAnnotation.Type\022 \n\006"
      "points\030\003 \003(\0132\020.foxglove.Point2\022\'\n\016outlin"
      "e_colors\030\004 \003(\0132\017.foxglove.Color\022#\n\nfill_"
      "color\030\005 \001(\0132\017.foxglove.Color\"M\n\004Type\022\013\n\007"
      "UNKNOWN\020\000\022\n\n\006POINTS\020\001\022\r\n\tLINE_LOOP\020\002\022\016\n\n"
      "LINE_STRIP\020\003\022\r\n\tLINE_LIST\020\004b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 435);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "foxglove/PointsAnnotation.proto", &protobuf_RegisterTypes);
  ::protobuf_foxglove_2fColor_2eproto::AddDescriptors();
  ::protobuf_foxglove_2fPoint2_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobuf_2ftimestamp_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_foxglove_2fPointsAnnotation_2eproto
namespace foxglove {
const ::google::protobuf::EnumDescriptor* PointsAnnotation_Type_descriptor() {
  protobuf_foxglove_2fPointsAnnotation_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_foxglove_2fPointsAnnotation_2eproto::file_level_enum_descriptors[0];
}
bool PointsAnnotation_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const PointsAnnotation_Type PointsAnnotation::UNKNOWN;
const PointsAnnotation_Type PointsAnnotation::POINTS;
const PointsAnnotation_Type PointsAnnotation::LINE_LOOP;
const PointsAnnotation_Type PointsAnnotation::LINE_STRIP;
const PointsAnnotation_Type PointsAnnotation::LINE_LIST;
const PointsAnnotation_Type PointsAnnotation::Type_MIN;
const PointsAnnotation_Type PointsAnnotation::Type_MAX;
const int PointsAnnotation::Type_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void PointsAnnotation::InitAsDefaultInstance() {
  ::foxglove::_PointsAnnotation_default_instance_._instance.get_mutable()->timestamp_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
  ::foxglove::_PointsAnnotation_default_instance_._instance.get_mutable()->fill_color_ = const_cast< ::foxglove::Color*>(
      ::foxglove::Color::internal_default_instance());
}
void PointsAnnotation::clear_timestamp() {
  if (GetArenaNoVirtual() == NULL && timestamp_ != NULL) {
    delete timestamp_;
  }
  timestamp_ = NULL;
}
void PointsAnnotation::clear_points() {
  points_.Clear();
}
void PointsAnnotation::clear_outline_colors() {
  outline_colors_.Clear();
}
void PointsAnnotation::clear_fill_color() {
  if (GetArenaNoVirtual() == NULL && fill_color_ != NULL) {
    delete fill_color_;
  }
  fill_color_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PointsAnnotation::kTimestampFieldNumber;
const int PointsAnnotation::kTypeFieldNumber;
const int PointsAnnotation::kPointsFieldNumber;
const int PointsAnnotation::kOutlineColorsFieldNumber;
const int PointsAnnotation::kFillColorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PointsAnnotation::PointsAnnotation()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_foxglove_2fPointsAnnotation_2eproto::scc_info_PointsAnnotation.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:foxglove.PointsAnnotation)
}
PointsAnnotation::PointsAnnotation(const PointsAnnotation& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      points_(from.points_),
      outline_colors_(from.outline_colors_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_timestamp()) {
    timestamp_ = new ::google::protobuf::Timestamp(*from.timestamp_);
  } else {
    timestamp_ = NULL;
  }
  if (from.has_fill_color()) {
    fill_color_ = new ::foxglove::Color(*from.fill_color_);
  } else {
    fill_color_ = NULL;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:foxglove.PointsAnnotation)
}

void PointsAnnotation::SharedCtor() {
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(type_));
}

PointsAnnotation::~PointsAnnotation() {
  // @@protoc_insertion_point(destructor:foxglove.PointsAnnotation)
  SharedDtor();
}

void PointsAnnotation::SharedDtor() {
  if (this != internal_default_instance()) delete timestamp_;
  if (this != internal_default_instance()) delete fill_color_;
}

void PointsAnnotation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PointsAnnotation::descriptor() {
  ::protobuf_foxglove_2fPointsAnnotation_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_foxglove_2fPointsAnnotation_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PointsAnnotation& PointsAnnotation::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_foxglove_2fPointsAnnotation_2eproto::scc_info_PointsAnnotation.base);
  return *internal_default_instance();
}


void PointsAnnotation::Clear() {
// @@protoc_insertion_point(message_clear_start:foxglove.PointsAnnotation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  points_.Clear();
  outline_colors_.Clear();
  if (GetArenaNoVirtual() == NULL && timestamp_ != NULL) {
    delete timestamp_;
  }
  timestamp_ = NULL;
  if (GetArenaNoVirtual() == NULL && fill_color_ != NULL) {
    delete fill_color_;
  }
  fill_color_ = NULL;
  type_ = 0;
  _internal_metadata_.Clear();
}

bool PointsAnnotation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:foxglove.PointsAnnotation)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .google.protobuf.Timestamp timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_timestamp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .foxglove.PointsAnnotation.Type type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::foxglove::PointsAnnotation_Type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .foxglove.Point2 points = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_points()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .foxglove.Color outline_colors = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_outline_colors()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .foxglove.Color fill_color = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_fill_color()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:foxglove.PointsAnnotation)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:foxglove.PointsAnnotation)
  return false;
#undef DO_
}

void PointsAnnotation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:foxglove.PointsAnnotation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_timestamp(), output);
  }

  // .foxglove.PointsAnnotation.Type type = 2;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  // repeated .foxglove.Point2 points = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->points_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->points(static_cast<int>(i)),
      output);
  }

  // repeated .foxglove.Color outline_colors = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->outline_colors_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->outline_colors(static_cast<int>(i)),
      output);
  }

  // .foxglove.Color fill_color = 5;
  if (this->has_fill_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_fill_color(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:foxglove.PointsAnnotation)
}

::google::protobuf::uint8* PointsAnnotation::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:foxglove.PointsAnnotation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_timestamp(), deterministic, target);
  }

  // .foxglove.PointsAnnotation.Type type = 2;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  // repeated .foxglove.Point2 points = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->points_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->points(static_cast<int>(i)), deterministic, target);
  }

  // repeated .foxglove.Color outline_colors = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->outline_colors_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->outline_colors(static_cast<int>(i)), deterministic, target);
  }

  // .foxglove.Color fill_color = 5;
  if (this->has_fill_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_fill_color(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foxglove.PointsAnnotation)
  return target;
}

size_t PointsAnnotation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foxglove.PointsAnnotation)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .foxglove.Point2 points = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->points_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->points(static_cast<int>(i)));
    }
  }

  // repeated .foxglove.Color outline_colors = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->outline_colors_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->outline_colors(static_cast<int>(i)));
    }
  }

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->has_timestamp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *timestamp_);
  }

  // .foxglove.Color fill_color = 5;
  if (this->has_fill_color()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *fill_color_);
  }

  // .foxglove.PointsAnnotation.Type type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PointsAnnotation::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:foxglove.PointsAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  const PointsAnnotation* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PointsAnnotation>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:foxglove.PointsAnnotation)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:foxglove.PointsAnnotation)
    MergeFrom(*source);
  }
}

void PointsAnnotation::MergeFrom(const PointsAnnotation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:foxglove.PointsAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  points_.MergeFrom(from.points_);
  outline_colors_.MergeFrom(from.outline_colors_);
  if (from.has_timestamp()) {
    mutable_timestamp()->::google::protobuf::Timestamp::MergeFrom(from.timestamp());
  }
  if (from.has_fill_color()) {
    mutable_fill_color()->::foxglove::Color::MergeFrom(from.fill_color());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void PointsAnnotation::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:foxglove.PointsAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PointsAnnotation::CopyFrom(const PointsAnnotation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foxglove.PointsAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PointsAnnotation::IsInitialized() const {
  return true;
}

void PointsAnnotation::Swap(PointsAnnotation* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PointsAnnotation::InternalSwap(PointsAnnotation* other) {
  using std::swap;
  CastToBase(&points_)->InternalSwap(CastToBase(&other->points_));
  CastToBase(&outline_colors_)->InternalSwap(CastToBase(&other->outline_colors_));
  swap(timestamp_, other->timestamp_);
  swap(fill_color_, other->fill_color_);
  swap(type_, other->type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PointsAnnotation::GetMetadata() const {
  protobuf_foxglove_2fPointsAnnotation_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_foxglove_2fPointsAnnotation_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace foxglove
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::foxglove::PointsAnnotation* Arena::CreateMaybeMessage< ::foxglove::PointsAnnotation >(Arena* arena) {
  return Arena::CreateInternal< ::foxglove::PointsAnnotation >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
